### ISSUE TITLE
Material Components redesign tracker

### ISSUE THREAD

**Issue by MSF-Jarvis** [MSF-Jarvis/wireguard-kt#41]
- [ ] TunnelCreatorActivity has no action bar to save items
- [x]  ~~AMOLED/Dark themes have zero distinction between bottom bar and window background~~ (f17847dc978f72138dcef411bc66b460de47787d)
- [ ] Is adding a bottom margin really the best way to ensure bottombar doesn't overlap with peers in Tunnel{Editor,Creator} flows?
- [ ] Snackbars need to be readjusted to show above the BottomAppBar
- [ ] Navigation button needs to be change to a back button when we move to inner fragments

**Comment by MSF-Jarvis** [comment]
The bottombar redesign is abandoned for now
