### ISSUE TITLE
Regression checklist

### ISSUE THREAD

**Issue by MSF-Jarvis** [MSF-Jarvis/wireguard-kt#56]
Current known regressions from the `0.0.20180929` tagged release.

- [x] Deleting individual tunnels is absolutely haywire
- [x] Dark and black elements show inconsistently in themes
- [x] Selecting the public key field in the Interface card causes a crash
- [x] Tunnel import doesn't show user friendly errors
- [ ] Snackbars in tunnel editor overlap with the add peer button
